### ISSUE TITLE
Download for specific fic stuck at "Fetched remote file X/X"

### ISSUE THREAD

**Issue by ColossusSteppes** [daniel-j/fimfic2epub#56]
When trying to download [this fic](https://www.fimfiction.net/story/234937/fractured-sunlight) and [this fic](https://www.fimfiction.net/story/78582/), it gets stuck fetching remote images.

For the first one, it may be due to the images being hosted on imgbox, which isn't the most common hosting site, but for the second one I'm not sure.

![image](https://github.com/daniel-j/fimfic2epub/assets/106880608/2af5a3c9-8425-49f9-88dc-1874a0708264)

It happens on both the Firefox and Chrome versions

**Comment by daniel-j** [comment]
Fixed now in latest update. Firefox addon has been updated and Chrome extension update is pending review.

The image in chapter 13 for the first fic you listed couldn't be downloaded because it's 404 (same error on fimfiction.net). For the second fix it also has an image that has been deleted. Not Fimfiction/fimfic2epub's fault.
